name: Test
on:
  - pull_request

jobs:
  release:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm t -- --coverage

      - name: Run build
        run: npm run build

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
